### PR TITLE
FTH232H: Make compatible with Python3

### PR DESCRIPTION
**Pull request by vestom**
- Fix some indentations (tab to spaces)
- Convert use of str() to bytes()
- Append b' to byte literals
- Fix some integer divisions / -> //

Tested with NeoPixel_FT232H example on both Python 2.7 and 3.7

### CODE REVIEW

**Comment by mpratt14** [comment]
> Fix some indentations (tab to spaces)

Does python 3 really complain about that? I can never figure out which editor is best to use...

> Convert use of str() to bytes()

Why? I see the str() function in both python 2 and 3 and they seem to be the same for this usage. Is there any advantage to bytes()?

> Fix some integer divisions / -> //

That does make it look cleaner, but there is no need to force int division, as the input should always be an int anyway as its just a count of bytes to read or write. There is never going to be a floating value or decimal involved here...although I'm not sure what would happen if you input a decimal...
I would say its better to just make sure the input is an int and convert to int with int() if it isnt. It would be better to be type-safe, if we even care to be this exact. If you make a float variable with a decimal, and you force int division with the '//', it is still going to be a float type and not an int type, for example:

`>>> a = 25.245
>>> a
25.245
>>> a/2
12.6225
>>> b = a/2
>>> c = a//2
>>> b
12.6225
>>> c
12.0
>>> type(b)
<type 'float'>
>>> type(c)
<type 'float'>
>>> A = int(a)
>>> type(A)
<type 'int'>
>>> c
12.0
>>> A
25
>>> A/2
12
>>> A//2
12
>>> A = a//2
>>> A
12.0
>>> type(A)
<type 'float'>
>>> `


Other than that it looks fine

**Comment by vestom** [comment]
Hi,
Well none of the fixes were made to make the code "cleaner", but due to real run-time errors when running Python3...
> Fix some indentations (tab to spaces)
`TabError: inconsistent use of tabs and spaces in indentation`
Python3 is apparently a bit more picky about consistent use of whitespace - which is probably a good thing.
> Convert use of str() to bytes()
`TypeError: expected bytes, str found`
In Python2 bytes and strings are exactly the same. However in Python3 strings are unicode encoded text, which is not what we want for a low level I/O driver. Specifically the ftdi1 read/write functions uses bytes in Python3.
> Fix some integer divisions / -> //
`TypeError: slice indices must be integers or None or have an __index__ method`
Division works differently in Python3 compared to your Python2 examples above. A "normal" division will always return a float (`4/2 => 2.0`) so explicit integer division is required.

**Comment by vestom** [comment]
... Just an additional observation I have made for myself: When coding for Python3, the code tends to be largely backwards compatible with Python2, whereas code tested only in Python2 will most often not work in Python3 without changes. So I highly recommend using Python3 for any new code :-)

**Comment by mpratt14** [comment]
Wow, that blew my mind that the differences between the two are on such a basic level as division. Also, I'm surprised that Python 2 doesn't have problems with tabs vs spaces as well...because that makes more sense to me when considering what tabs are really for....

Thanks for explaining str() vs bytes(), I couldn't spot the difference where Unicode is the default in py3.

I did some further digging into the difference between / and // in both pythons. Which led me to [this](https://www.python.org/dev/peps/pep-0238/). It turns out that // is exactly the same in both versions, which they call "floor division" everywhere I look. The / style is the only one they changed in order to handle all combinations of integer, complex, and float values without type errors.

However, this means that the // still doesn't guarantee the result is an int, but rather if any operand isn't an int, the result is going to be the non-int. If libFTDI doesn't force values to be int then we probably should. 

So for python 3 the best resolution is actually to have both // and int() in the line I guess...

BTW it would be awesome if you can help us make the library officially compatible with both 2 and 3.

**Comment by vestom** [comment]
I can help some, but am currently only using the SPI functionality. Unfortunately, Python being an interpreted language, the error messages are mainly run-time errors and you need to exercise all the code-paths to be sure - which is also why the changes in this pull request are very much a "direct conversion". (I did not want to make further changes in the code paths I cannot test!). But please reach out, if you need some specific help.

I highly recommend all developers changing to Python 3, to get the necessary test coverage. Python 2 is largely dead by now, and beginning to be phased out. Official support will end by the start of 2020! [https://pythonclock.org/](https://pythonclock.org/). It is fairly easy to change to Python 3 when you learn about the handful of major changes. Also the interpreter helps a lot. My personal opinion is that, although initially irritating, the changes actually make sense and make the language more consistent.

Regarding division, most of the changes are in the form `len(data)//2`, which are inherently OK. The only other two examples are in `read()` and `bulkread()`, where length is passed by argument and only integers makes sense. Python 2 will also throw an error, if a float argument is used.

**Comment by mpratt14** [comment]
Same, I only use it for SPI. I would get to working on the rest of the library eventually, but only things that are obviously not py3 compatible until I also have a way to test as much of the rest of it as I can, at the very least I2C.

The developers of this library don't really support it anymore and are working on merging it with their CircuitPython series of libraries, which is designed for py3. I still like this library and don't see it as deprecated but rather just needs much love and care, and it can use as much help as you can give.

One of my ideas is making a library that will simulate traditional JTAG for routers over USB, I've had only a little luck getting a simulated LPT port. Also, a way to use the Virtual COM functionality without the VCP driver...all of this requires extra steps outside of python code and its kind of beyond the scope of the library a little...

Anyway, I was thinking that since we can force arguments expected as int to be int, that we might as well do so. The less that the user is required to debug the better, no?

**Pull request merged**
