### PR TITLE
Support for the C.H.I.P. Computer

### PR DESCRIPTION
**Pull request by xtacocorex**
This pull request adds support for the CHIP by NextThingCo.  The code is similar to the BeagleBone Black, as I've ported the adafruit_beaglebone_io_python library to the CHIP and called it CHIP_IO.  There are no CHIP HW specifics in this library as I've put everything into CHIP_IO.

The following code has been touched: 
GPIO.py -> Adds a CHIP GPIO Device
Platform.py -> Adds the CHIP to be an allowed platform
I2C.py -> Adds the ability to use get the default CHIP I2C bus
PWM.py -> Adds the ability to get the HW and SW PWM for the CHIP

Limitations:
- HW PWM on the CHIP requires, at the moment, a custom kernel and DTS overlay
- Has not been verified with the Adafruit native i2c and spi library

### CODE REVIEW

**Comment by futurejones** [comment]
Thanks, this is awesome!

**Comment by zcseke** [comment]
Thanks for your work! From a C.H.I.P-per

**Comment by streamnsight** [comment]
+1

**Comment by nio101** [comment]
+1!

**Comment by peisenhower** [comment]
+1

**Comment by tdicola** [comment]
Thanks for making the change and sending it earlier!  I'm going to close this as we're working on an update to use the latest Linux kernel's user space I/O facilities for GPIO access.  This will enable support for CHIP and all other boards in a more general way.  Thanks!

**Pull request closed without merging**
